[package]
name = "monte-carlo"
version = "0.1.0"
authors = ["suhas"]
edition = "2018"

[profile.release]
debug=true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.7.3"
rand_distr="0.2.2"
rayon="1.3.0"
num_cpus="1.13.0"